### ISSUE TITLE
light mode bug

### ISSUE THREAD

**Issue by OmerBotbol** [davidbinneun/pre-course-2021-final-boilerplate#2]
when you set the app on light mode and refresh the page it's turns back to dark mode

step to reproduce:
1. change to light mode
2. refresh the page

expected result:
stays in light mode

acrual result:
change back to dark mode

**Comment by listguy** [comment]
👌👌

**Comment by davidbinneun** [comment]
Thank you for your feedback! this issue was fixed in the last update.
