### ISSUE TITLE
Priority display bug

### ISSUE THREAD

**Issue by noavrd** [davidbinneun/pre-course-2021-final-boilerplate#3]
when you add a long word to the task the priority background is not on all the task div
steps:
1 - click on add task
2 - the task adds to the list

expected result:
the priority background height is the same size as the div height.

actual result:
the priority background height is smaller than the same size as the div height.

**Comment by listguy** [comment]
👌👌

**Comment by davidbinneun** [comment]
Thank you for your feedback! this is intended and will not be changed.
